version: '3.8'

services:
  attacker:
    image: ubuntu:latest
    command: sleep infinity
    # volumes:
      # - ./attacker:/data
    depends_on:
      - osken
    networks:
      external:

  osken:
    image: scc-registry.lancs.ac.uk/teaching/scc_365/ken:24
    command: sh -c /scripts/entrypoint.sh & sleep infinity
    volumes:
      # - ./osken:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      external:
        ipv4_address: 10.10.0.100
        mac_address: 00:00:0a:0a:00:64
      internal:
        ipv4_address: 10.11.0.100
        mac_address: 00:00:0a:0b:00:64

  nginx:
    image: nginx:latest
    # volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - osken
    networks:
      internal:

networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/24
          gateway: 10.11.0.1

volumes:
  db_data: