version: '3.8'

services:
  attacker:
    image: bdnr/net-tools
    privileged: true
    command: su -c "sh /boot.sh && sleep infinity"
    volumes:
      - ./attacker/boot.sh:/boot.sh
    # volumes:
      # - ./attacker:/data
    # depends_on:
    #   - osken
    networks:
      external:
        mac_address: ba:2f:0b:70:f1:56

  osken:
    image: scc-registry.lancs.ac.uk/teaching/scc_365/ken:24
    command: sh -c "/scripts/entrypoint.sh && sh /boot.sh && sleep infinity"
    privileged: true
    volumes:
      # - ./osken:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./osken/boot.sh:/boot.sh
    networks:
      external:
        ipv4_address: 10.10.0.100
        mac_address: 00:00:0a:0a:00:64
      internal:
        ipv4_address: 10.11.0.100
        mac_address: 00:00:0a:0b:00:64

  nginx:
    image: nginx:alpine
    privileged: true
    entrypoint: su -c "ip route add 10.10.0.0/24 via 10.11.0.100 dev eth0 && arp -s 10.11.0.100 00:00:0a:0b:00:64 && nginx -g 'daemon off;'"
    # volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    # depends_on:
    #   - osken
    networks:
      internal:
        mac_address: 56:84:5D:5A:9B:F1

networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.0.0/24
          gateway: 10.11.0.1

volumes:
  db_data: